GAuth_DIP_AuthenticateGAuth:
  - 'lambda/packages/authenticateGAuth/**/*'
GAuth_DIP_FetchUser:
  - 'lambda/packages/fetchUser/**/*'
GAuth_DIP_FetchDiscordUserInformation:
  - 'lambda/packages/fetchDiscordUserInformation/**/*'
