[package]
authors = ["loxygenk <me@loxygen.dev>"]
edition = "2018"
name = "gadis_bot"
version = "0.1.0"

[dependencies]
async-trait = "*"
tokio = { version = "*", features = ["macros", "rt", "rt-multi-thread"] }
