[package]
name = "gadis_api"
version = "0.1.0"
authors = ["loxygenK <me@loxygen.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
