on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deploy:
    name: Deploy projects to AWS Lambda
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: read

    env:
      zip_artifact: gadis-codedeploy-source.zip

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b8c74de753fbcb4868bf2011fb2e15826ce973af
        with:
          role-to-assume: ${{ secrets.EC2_DEPLOY_ASSUMING_ROLE }}
          role-session-name: GitHubAction_ECDeploy
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy file to S3 and start deploying
        run: |
          zip -r -o ${{ env.zip_artifact }} bot
          aws s3 cp ${{ env.zip_artifact }} s3://${{ secrets.EC2_DEPLOY_S3_BUCKET_NAME }}

